jolicode/secret-santa

- README.md
- composer.json
- composer.lock
- src/SantaKernel.php
Fix #8.
- updated everything, it was easy
- just one fix to make in the framework config: I had to enable 'assets' because the Twig `@Twig/Exception/exception_full.html.twig` use it... :hankey: 
Changelogs summary:
- fabpot/php-cs-fixer removed (installed version was v1.11.6)
- symfony/polyfill-apcu removed (installed version was v1.2.0)
- symfony/polyfill-php54 removed (installed version was v1.2.0)
- symfony/polyfill-php55 removed (installed version was v1.2.0)
- ircmaxell/password-compat removed (installed version was v1.0.4)
- symfony/security-acl removed (installed version was v3.0.0)
- psr/http-message updated from 1.0 to 1.0.1
See changes: https://github.com/php-fig/http-message/compare/1.0...1.0.1
Release notes: https://github.com/php-fig/http-message/releases/tag/1.0.1
- …
> Update to Symfony 3.1 and some minor fixes

- public/style.css
- templates/content/homepage.html.twig
Rewrite the description without quote:
Move and complete the quote from Wikipedia in a new paragraph and mention alternative names:
> Add new wording about Secret Santa alternative names

- src/Discord/ApiHelper.php
- src/Discord/UserExtractor.php
Also, this PR centralizes timeout logic in a single and unit tested service (not a big fan of the callables system though)
> Use pagination to retrieve Discord users

- templates/santa/run.html.twig
Looks like this:
But will be different in other systems/browsers.
> Add 🔎 on the Search Bar to make it more visible

- config/routes.yaml
- public/style.css
- src/Controller/SantaController.php
- src/Santa/MessageDispatcher.php
- templates/content/faq.html.twig
- templates/santa/finish.html.twig
- templates/santa/run.html.twig
- templates/santa/send_messages.html.twig
Fix #100
Replace the retry workflow.
When submitting the form, the santa is saved in session then the user is redirected to this page (note: this new page can be safely refreshed):
Javascript will continously ask the server to send the remaining message as soon a timeout is reached. At each timeout iteration, the progress bar is updated - timeout was lowered to 5 seconds to allow the progress bar to be refreshed more often, should make user more confident.
When all the messages are sent or if an error happened, the user is redirected to the finish page, as before.
> Add automatic retry message sending on timeout

- config/services.yaml
Fix #110 
Note: by default, Predis session handler [uses](https://github.com/nrk/predis/blob/v1.1/src/Session/Handler.php#L42) the `session.gc_maxlifetime` PHP config with seems to be 1440 by default.
We will now use a lifetime of 2 hours.
Note 2: Symfony session lives 4 days but as the redis key expire before this does not change anything
Note 3: Cookie session lives the whole browser session time
> Increase session duration

- src/Santa/Rudolph.php
Not sure we need it but I just got an issue with shuffle on a private project. Shuffle always outputted the same array (no idea why) and the only fix we found was to call `mt_srand()` before `shuffle()`
Not tested yet :man_shrugging:
> Ensure shuffle's seed change everytime

- composer.json
- composer.lock
Massive composer update, and upgrading Slack PHP Api client to v3.0.0 (Jane 6).
Also remove 2 forks as the upstream projects have been released.
> Upgrade Slack PHP API client and all other dependencies

- src/Discord/ApiHelper.php
See #167 
The HTTP Client we use have a ratelimiter: https://github.com/restcord/restcord/blob/master/src/RateLimit/RateLimiter.php
By default the state is stored in memory.
Our previous implementation was always rebuiling a new Client, so in the extractForGuild loop, it was always a fresh client and fresh rate limiter without the informations from the previous request.
This PR use always the same Client and that should allow us to benefit from the RateLimiter for user extraction AND message sending.
> Refactor the Discord Api Helper to use the RateLimiter

- config/routes.yaml
- public/style.css
- src/Controller/SantaController.php
- src/Discord/ApiHelper.php
- src/Discord/MessageSender.php
- src/Model/SecretSanta.php
- src/Slack/MessageSender.php
- src/Zoom/MessageSender.php
- templates/santa/application/notes_discord.html.twig
- templates/santa/application/notes_slack.html.twig
- templates/santa/application/notes_zoom.html.twig
- templates/santa/notes.html.twig
- templates/santa/run.html.twig
This PR will add a second step (if the admin wants to add notes) and fixes #136.
The new form:
I added a "Add notes for your participants before sending" button that will bring you to a second form:
Where you can add notes on each lines.
Theses notes will be send to the gifter.
And the message output on Discord:
> Allow to send notes

- composer.json
- composer.lock
- config/bundles.php
- src/Controller/SlackController.php
- src/Slack/ClientFactory.php
- src/Slack/MessageSender.php
- src/Slack/SlackProvider.php
- src/Slack/UserExtractor.php
- symfony.lock
Before 4th december, we need to move to v2 of Slack OAuth2 endpoint. The new version of our Slack must first be approved by Slack first before. Then we will need to publish it live and deploying this PR in production at the same time I guess.
> Use latest Slack auth

- src/Santa/Spoiler.php
- tests/Santa/SpoilerTest.php
- Json encoding of only the senders (receivers can be deducted from senders list)
- gzencode of the json object for better compression
- still base64 encode the result to keep only alphanumerical chars
I just made a test with 1000 participants with long name, the final code is only 3.3k chars long \o/
> Make spoil code shorter

- README.md
- composer.json
- composer.lock
This PR use the brand new release of https://github.com/jolicode/slack-php-api and also upgrade Symfony to the latest minor.
> Upgrade Slack PHP API Client to 4.0 and Symfony to 5.2.1

- config/services.yaml
- infrastructure/docker/services/php-base/etc/php/7.4/mods-available/app-default.ini
- public/.user.ini
We had:
- 2h TTL on Predis / Redis (from services.yaml)
- default PHP `session.gc_maxlifetime` to 24 minutes
- `cookie_lifetime` of 0 which is great
Now everything can last 3 hours, no more session disappearing in the middle of a Secret Santa.
Configuring a PHP.INI value on Clever Cloud require a .user.ini file in the Webroot (public?!), that's quite strange to have PHP configuration here but not a concern.
https://www.clever-cloud.com/doc/deploy/application/php/php-apps/#configure-your-php-application
> Increase the PHP Session timeout to 3 hours

- .github/workflows/ci.yml
- Pipfile
- Pipfile.lock
- config/routes.yaml
- src/Controller/ZoomController.php
- templates/content/homepage.html.twig
- templates/santa/pre_auth_warning.html.twig
Ref #142 
We are not going to have a very nice user experience on Zoom until the API is improved on their side, so let's add a warning.
WDYT?
> Add a Warning pre-auth page for Zoom users #142

- templates/content/faq.html.twig
Hi,
This tiny PR will fix : 
- 1 typo in `templates/content/faq.html.twig`
Best! :robot:
> docs: fix typo in templates/content/faq.html.twig

- src/Application/SlackApplication.php
- src/Controller/SantaController.php
- src/Form/MessageType.php
- src/Form/ParticipantType.php
- src/Model/Config.php
- src/Model/SecretSanta.php
- src/Statistic/StatisticCollector.php
- templates/santa/application/message_slack.html.twig
- templates/santa/application/participants_discord.html.twig
- templates/santa/application/participants_slack.html.twig
- templates/santa/application/participants_zoom.html.twig
- templates/santa/message.html.twig
- templates/santa/participants.html.twig
- tests/Controller/SantaControllerTest.php
- tests/Santa/SpoilerTest.php
Added an object that stores all the necessary data to create a Secret Santa, and passed it in session instead of all the variables that we used to.
Also updated the SecretSanta object with the same idea, replaced a bunch of parameters (not all) by one single $config parameter containing most of the data needed.
Tests and QA should be taken care of as well
> Add Config object to remove session variables

- src/Controller/SantaController.php
- src/Model/SecretSanta.php
- src/Santa/MessageDispatcher.php
- templates/santa/finish.html.twig
- tests/Controller/SantaControllerTest.php
Fix #224 
Made it so that all messages are sent to the participants, even when some don't go through.
All the messages that did not succeed are shown to the admin on the final page, from there they can choose to retry sending only these remaining messages.
> Upgrade message dispatching

- src/Application/DiscordApplication.php
- src/Application/SlackApplication.php
- src/Controller/DiscordController.php
- src/Controller/SlackController.php
- src/Discord/ApiHelper.php
- src/Model/ApplicationToken.php
Fix #239 
Trim the tokens for Slack and Discord to make them lighter and not store as much useless info in session as we used too (like emojis).
Also changed some methods a bit for Discord to make less API calls
> Trim tokens for Slack and Discord

- src/Application/WebexApplication.php
- src/Controller/SantaController.php
- src/Controller/WebexController.php
- src/Discord/MessageSender.php
- src/Model/Config.php
- src/Slack/MessageSender.php
- src/Webex/MessageSender.php
- src/Webex/UserExtractor.php
- templates/santa/application/participants_webex.html.twig
- templates/santa/participants.html.twig
Refs: #272
After a discussion with the support, they suggested I use the "Spaces" instead of trying to get the whole company directory.
That way the Admin permission is not needed anymore.
Big change: we now store the GROUPS in the Config as well.
> feat(webex): Use Space to fetch user friends, remove admin need

- src/Controller/WebexController.php
- src/Webex/MessageSender.php
- templates/content/faq.html.twig
When talking with the bot, it's nice to get an answer, even if it's a link to the website.
That's what this PR bring:
The only requirement is the creation of a webhook like this:
```
curl -X POST --location "https://webexapis.com/v1/webhooks" \
-H "Authorization: Bearer BOT-TOKEN" \
-H "Content-Type: application/json" \
-d "{
\"name\": \"production-webhook\",
\"targetUrl\": \"https://secret-santa.team/bot/webex\",
\"resource\": \"messages\",
\"event\": \"created\"
}"
```
Also added a note in the FAQ regarding revocation.
> feat(webex): Handle messages sent to the bot

- src/Webex/UserExtractor.php
We got a 404 error on a room membership API:
```
HTTP/2 404  returned for "https://webexapis.com/v1/memberships?roomId=XXX".
```
I think we can safely ignore those. Maybe this room was private or something like this.
> fix(webex): Ignore rooms we cannot use / list members

- .github/workflows/ci.yml
- **ci: update some actions version**
- **ci: format yaml**
> ci: update some actions version

- src/Discord/ApiHelper.php
- src/Slack/UserExtractor.php
Follow-up of https://github.com/jolicode/secret-santa/pull/307
Also remove retry duplicated logic for Slack client.
> Do not catch HTTP exception for Discord to better handle 403
