src/SecretDispatcher.php
=> Fix typo :uk:

src/Controller/SantaController.php, src/SantaKernel.php
Use the autowiring feature introduced in Symfony 2.8.
=> Use autowiring

.travis.yml, src/SantaKernel.php, src/UserExtractor.php, tests/SantaControllerTest.php
Waiting for travis to be configured on this repo (require admin github access) to trigger a build and verify it works :tm:
=> Add some functionnal tests :oncoming_police_car:

README.md, views/index.html.twig, views/layout.html.twig
=> Improve wording and make sure we comply with Slack ToS / Guidelines

views/index.html.twig, web/style.css
I just thought it could be interesting to readd this content back
=> Add a "Why" block inspired from the old content

src/Controller/SantaController.php, src/SantaKernel.php
We will probably never get slack command so this code is quite useless.
=> Remove useless code :haircut:

Resources/views/finish.html.twig, Resources/views/summary.txt.twig, src/Controller/SantaController.php, src/Result.php, src/SantaKernel.php, src/SecretDispatcher.php, tests/SantaControllerTest.php, web/style.css
=> Download repartition summary

Resources/TwigBundle/views/Exception/error404.html.twig, Resources/TwigBundle/views/Exception/error500.html.twig, Resources/views/finish.html.twig, Resources/views/layout.html.twig, Resources/views/run.html.twig, tests/SantaControllerTest.php, web/style.css
- remove the wiggly wiggly on some links
- fix error pages
- fix footer
=> 🕮 Improve wording and design stuff

src/Controller/SantaController.php
=> Remove xss protection because Slack handle it correctly

src/UserExtractor.php
By default, slackbot is not marked as a bot ¯\\\_(ツ)\_/¯
=> Do not show slackbot in user list

src/Controller/SantaController.php, src/Rudolph.php, src/SecretDispatcher.php, src/SecretSanta.php, src/UserExtractor.php, tests/Controller/SantaControllerTest.php
=> Add scalar and return typehint everywhere

public/index.php
Ref https://github.com/symfony/recipes/pull/156
=> Update latest flex structure

templates/santa/finish.html.twig
After they did their secret santa is the best place to promote the Hall Of Fame 😎
=> Add "Hall of Fame" promotion to the finish page

public/style.css, src/SecretDispatcher.php, src/SecretSanta.php, templates/santa/finish.html.twig, tests/Controller/SantaControllerTest.php
=> Better error page when issue with Slack sending

.env.dist, README.md, templates/layout.html.twig
Add Clever Cloud as hosting sponsor and fix some documentation and links.
=> Updating the README and adding new hosting provider sponsor to footer

public/style.css, src/EventListener/RedirectOldDomainSubscriber.php, templates/_seo.html.twig, templates/content/hall_of_fame.html.twig, templates/content/homepage.html.twig, templates/layout.html.twig
=> New branding

composer.lock, templates/santa/finish.html.twig, templates/santa/run.html.twig
When I run test on master, I had an issue due to deprecated usage from Nelmio getCSPNonce function argument
=> fix test error due to missing csp_nonce argument

config/services.yaml
=> Increase HTTP-timeouts

config/routes.yaml, public/style.css, src/Controller/ContentController.php, templates/content/privacy_policy.html.twig, templates/content/terms.html.twig, templates/layout.html.twig
=> Add pages for terms ad privacy policy

templates/_seo.html.twig, templates/content/homepage.html.twig, templates/layout.html.twig, templates/santa/finish.html.twig, tests/Controller/SantaControllerTest.php
- Better SEO (I think)
- Change the wording on the error page, move the list of errors out of the view, move the "continue" button up.
=> Wording changes for SEO and better "error" page

src/Discord/MessageSender.php
"Fix" for the "@invalid-user" issue.
=> Add a warning for Discord users because there is a bug on mobile

config/packages/framework.yaml, config/routes.yaml, public/style.css, src/Application/ApplicationInterface.php, src/Application/DiscordApplication.php, src/Application/SlackApplication.php, src/Controller/SantaController.php, src/Discord/MessageSender.php, src/Slack/MessageSender.php, templates/santa/application/run_discord.html.twig, templates/santa/application/run_slack.html.twig, templates/santa/run.html.twig
=> Add a way to try private message before final draw

config/packages/framework.yaml, public/style.css, src/Application/ApplicationInterface.php, src/Application/DiscordApplication.php, src/Application/SlackApplication.php, src/Controller/DiscordController.php, src/Controller/SantaController.php, src/Controller/SlackController.php, src/Discord/ApiHelper.php, src/Discord/UserExtractor.php, src/Exception/MessageSendFailedException.php, src/Group.php, src/Rudolph.php, src/Slack/ApiHelper.php, src/Slack/ClientFactory.php, src/Slack/MessageSender.php, src/Slack/UserExtractor.php, templates/santa/application/run_discord.html.twig, templates/santa/application/run_slack.html.twig, templates/santa/run.html.twig, tests/RudolphTest.php
On discord, a group is a Role.
On slack, a group is known as User Group.
I also tweaked the display to better see the selection summary instead of beeing stuck under the user list.
=> Add support for selecting user via their groups

src/Slack/MessageSender.php
Should fix #101 if I didn't make any mistake (hopefully I won't break anything, please double check!) :)
=> Message formatting update

composer.json, composer.lock, src/Controller/SantaController.php, src/Controller/SlackController.php, src/Slack/MessageSender.php, src/Slack/UserExtractor.php
First steps to introduce the new Slack feature.
WIP (Draft PR are not available here? :sob:)
=> Introducing Slack Block Kit for messaging the Secret Santa

Makefile, composer.json, composer.lock, config/packages/twig.yaml, config/routes/dev/twig.yaml, src/Controller/ContentController.php, src/Controller/SantaController.php, src/EventListener/HandleExceptionSubscriber.php, src/Santa/Rudolph.php, symfony.lock
In this PR, you can see *only* the update to SF 4.4.
Do not merge.
=> Upgrade to Symfony 4.4

public/style.css, templates/content/homepage.html.twig
Revert this PR when permission issue with Discord API is resolved
=> Temporarily discourage Discord usage for now 😢

config/packages/nelmio_security.yaml, public/.htaccess, tests/Controller/BaseWebTestCase.php, tests/Controller/ContentControllerTest.php, tests/Controller/DiscordControllerTest.php, tests/Controller/SantaControllerTest.php, tests/Controller/SlackControllerTest.php, tests/Controller/ZoomControllerTest.php
- Add HSTS
- Disable deprecated X-CSP
- Add Expect-CT header
- Update referrer-policy
=> Add missing security headers

public/style.css, templates/content/homepage.html.twig
Reverts jolicode/secret-santa#158
Yeah Discord finally solved our problem of permission \o/
=> Revert "Temporarily discourage Discord usage for now 😢"

composer.lock, infrastructure/docker/services/builder/Dockerfile
Update symfony/flex to be compatible with Composer 2
=> Support Composer 2

templates/content/faq.html.twig, templates/content/privacy_policy.html.twig
Clarify that data is stored in session and automatically deleted after few hours.
=> Clarify privacy policy

src/Controller/SantaController.php, templates/santa/message.html.twig
Fix #177 and #178
See commit messages for a changelog
=> Tweak message step

templates/content/faq.html.twig
Fix #184
I don't know if we really need to explain the following:
```
The application simply shuffle the participants, and then associate them "in a single loop":
user1 will offer to user2
user2 will offer to user3
...
userX will offer to user1
```
=> Explain the app works with odd number of participants

public/style.css, templates/content/stats.html.twig
Some minor presentation improvements.
=> Tweak HTML/CSS

composer.json, composer.lock, config/routes.yaml, config/routes/annotations.yaml, src/Controller/ContentController.php, src/Controller/DiscordController.php, src/Controller/SantaController.php, src/Controller/SlackController.php, src/Controller/ZoomController.php, src/Kernel.php, tasks.py
Required doctrine/annotations and changed all routes from `config/routes.yaml` to controller attributes
=> Change routing to attributes

src/Slack/MessageSender.php
( Fix #214 ) Removed unfurling of links when using Slack. The previews should not appear anymore 😊
=> Remove Slack unfurling

public/style.css, src/Application/ApplicationInterface.php, src/Application/DiscordApplication.php, src/Application/SlackApplication.php, src/Application/ZoomApplication.php, src/Controller/SantaController.php, src/Model/SecretSanta.php, src/Slack/MessageSender.php, templates/santa/application/message_slack.html.twig, templates/santa/message.html.twig
Added the option to schedule a secret santa for a later date when organizing it on Slack
Fix #208
=> Add scheduling for Slack

.github/workflows/ci.yml, public/style.css, src/Application/SlackApplication.php, src/Controller/SantaController.php, src/Discord/MessageSender.php, src/Slack/MessageSender.php, src/Zoom/MessageSender.php, templates/content/homepage.html.twig, templates/santa/application/message_slack.html.twig, templates/santa/application/participants_discord.html.twig, templates/santa/application/participants_slack.html.twig, templates/santa/application/participants_zoom.html.twig
Lot of fixes/tweaks. Among them:
- In the user summary, the cross to remove a user no longer worked since symfony form refacto
- about Slack scheduling section:
- we now allow for at least 10min in the future to avoid issues when sending messages take a lot of time
- the date input is now readonly
- a cross is added to clear the input correctly
- datepicker do not allow date in the past or too far in the future
- fix note inputs border-radius
- in the admin message:
- scheduling date is better integrated 
- tweak the message with some bold
=> Misc fixes

.env, composer.json, composer.lock, config/packages/framework.yaml, config/routes.yaml, config/services.yaml, public/index.php, src/Kernel.php, symfony.lock
Also, now using symfony/runtime :)
=> Update to Symfony 6.0 and use latest flex recipes

composer.json, composer.lock, src/Controller/DiscordController.php, src/Controller/SantaController.php
This should also fix the tests.
=> Upgrade PHPStan to 1.5 and fix a small newly discovered error

.github/workflows/ci.yml
- Update GitHub Action actions/checkout from v2 to v3
- Update GitHub Action actions/setup-python from v2 to v4
=> Update some GitHub Actions"

src/Webex/MessageSender.php
Refs: https://github.com/jolicode/secret-santa/pull/281#pullrequestreview-1736087889
=> fix(webex): Use a generated URL instead of hardcoded one in bot answer

public/style.css, src/Controller/SantaController.php, src/Model/Config.php, src/Model/SecretSanta.php, templates/content/faq.html.twig, templates/santa/application/validate_discord.html.twig, templates/santa/application/validate_slack.html.twig, templates/santa/application/validate_webex.html.twig, templates/santa/base.html.twig, templates/santa/finish.html.twig, templates/santa/message.html.twig, templates/santa/send_messages.html.twig, templates/santa/validate.html.twig
Also updated the design of the FAQ page when restyling `<details>` / `<summary>` tags:
=> Add a new step allowing to validate the secret repartition
